### ISSUE TITLE
Possible fix to the phantomJS select: Invalid argument

### ISSUE THREAD

**Issue by keyscores** [aldeed/meteor-browser-tests#3]
Regarding the long standing phantomJS issue: `select: Invalid argument`
Could it be possible that the PhantomJS implementation is not closing the page after the test is done? See the explanation here:
http://stackoverflow.com/questions/32430426/phantomjs-2-0-0-select-invalid-argument-error

**Comment by aldeed** [comment]
@keyscores Thanks for the link, but unfortunately I played around with closing the page and it didn't fix it.
