### ISSUE TITLE
Can't get phantomjs working

### ISSUE THREAD

**Issue by macsj200** [aldeed/meteor-browser-tests#4]
Hello, I'm trying to use your package, but when I run your code, it complains that I haven't added phantomjs-prebuilt. When I spin up a node instance inside of the directory, however, I am able to require the package with no issue. Do you have any idea why the code may not recognize that I have already installed the package?

Edit: getting the same issue with chrome as well.

**Comment by keyscores** [comment]
@macsj200  you should be installing https://github.com/DispatchMe/meteor-mocha
This repo is just a module of dispatch:mocha.

BTW: Try the electron/nightmare version option instead of phantomjs, when using dispatch:mocha.

**Comment by macsj200** [comment]
So I was trying to debug the issue, and I eventually arrived at this project. I think it has something to do with the way `test-packages` loads npm deps.

**Comment by IvanJov** [comment]
Having same issue, that's probably the issue with loading npm dependencies in `test-packages`, as @macsj200 said... Any idea how can we fix this?

**Comment by aldeed** [comment]
@macsj200 @IvanJov you are both encountering this when testing a package? I'm not sure if I have personally used it with `test-packages`. In most cases I've been using a test app shell (like in https://github.com/aldeed/meteor-collection2-core). But in theory it should be working. Does anyone have a minimal reproduction repo I can look at?

**Comment by macsj200** [comment]
I'm actually pretty unclear on best practices for making a meteor package depend on npm packages. Should I be creating a `package.json` file that enumerates dependencies?

Moreover, should I be using peer dependencies or absolute versions?

**Comment by aldeed** [comment]
@macsj200 I want to say that packages still only work with `Npm.depends`. You can include the test NPM packages with `Npm.depends` but then they'll be included outside of testing as well. Which I think is why I have been making test apps. Probably all we need is an `Npm.testDepends` added in Meteor core

**Comment by macsj200** [comment]
Alright, thanks for the help. I'll give that a shot.

**Comment by aldeed** [comment]
I had a chance to test this with test-packages and filed a Meteor issue here: https://github.com/meteor/meteor/issues/8577

**Comment by optunetobi** [comment]
We've had the same issue on our meteor-packages. Turned out as no `.meteor` folder was present, the package `phantomjs-prebuilt` not found, even when it correctly installed in `node_modules`.

Adding `.meteor/` by running `meteor` inside the package-folder fixed our issue.

Removing our Npm.depends did not matter, only package.json.

Hope this makes sense to anybody stumbling on this.
